"""initial tenant-safe schema"""
from alembic import op
import sqlalchemy as sa

revision = '20441dc9a106'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('login_throttles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('clients',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id')
    )
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=False)
    op.create_table('professionals',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=160), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("engagement in ('MEI','autonomo','CLT')"),
    sa.CheckConstraint('commission_bps between 0 and 10000'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id')
    )
    op.create_index(op.f('ix_professionals_business_id'), 'professionals', ['business_id'], unique=False)
    op.create_table('specialties',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id'),
    sa.UniqueConstraint('business_id', 'name')
    )
    op.create_index(op.f('ix_specialties_business_id'), 'specialties', ['business_id'], unique=False)
    op.create_table('professional_specialties',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'professional_id'], ['professionals.business_id', 'professionals.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'specialty_id'], ['specialties.business_id', 'specialties.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'professional_id', 'specialty_id')
    )
    op.create_table('services',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price_cents >= 0'),
    sa.ForeignKeyConstraint(['business_id', 'specialty_id'], ['specialties.business_id', 'specialties.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id')
    )
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(role = 'gestor' and professional_id is null) or (role = 'profissional' and professional_id is not null)"),
    sa.ForeignKeyConstraint(['business_id', 'professional_id'], ['professionals.business_id', 'professionals.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email'),
    sa.UniqueConstraint('business_id', 'id'),
    sa.UniqueConstraint('business_id', 'professional_id')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_table('attendances',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('professional_name', sa.String(length=160), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=False),
    sa.Column('service_name', sa.String(length=160), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("payment_method in ('pix','dinheiro','credito','debito')"),
    sa.CheckConstraint("status != 'rejected' or length(rejection_reason) > 0"),
    sa.CheckConstraint("status in ('pending','approved','rejected')"),
    sa.CheckConstraint('price_cents >= 0 and commission_cents >= 0 and commission_bps between 0 and 10000'),
    sa.ForeignKeyConstraint(['business_id', 'client_id'], ['clients.business_id', 'clients.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'created_by'], ['users.business_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'professional_id'], ['professionals.business_id', 'professionals.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'reviewed_by'], ['users.business_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'service_id'], ['services.business_id', 'services.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id'),
    sa.UniqueConstraint('business_id', 'request_key')
    )
    op.create_index(op.f('ix_attendances_business_id'), 'attendances', ['business_id'], unique=False)
    op.create_index(op.f('ix_attendances_created_at'), 'attendances', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendances_professional_id'), 'attendances', ['professional_id'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['users.business_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_business_id'), 'audit_events', ['business_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('payouts',
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('total_cents >= 0'),
    sa.ForeignKeyConstraint(['business_id', 'created_by'], ['users.business_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id'),
    sa.UniqueConstraint('business_id', 'request_key')
    )
    op.create_index(op.f('ix_payouts_business_id'), 'payouts', ['business_id'], unique=False)
    op.create_table('payout_items',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'attendance_id'], ['attendances.business_id', 'attendances.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'payout_id'], ['payouts.business_id', 'payouts.id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index(op.f('ix_payout_items_business_id'), 'payout_items', ['business_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_items_business_id'), table_name='payout_items')
    op.drop_table('payout_items')
    op.drop_index(op.f('ix_payouts_business_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_events_business_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_professional_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_created_at'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_business_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('professional_specialties')
    op.drop_index(op.f('ix_specialties_business_id'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_professionals_business_id'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('login_throttles')
    op.drop_table('businesses')
    # ### end Alembic commands ###
