"""commercial lifecycle platform and specialist onboarding"""
from alembic import op
import sqlalchemy as sa

revision = '3be600b16a15'
down_revision = 'e71f_identity_memberships'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_reference', sa.String(length=160), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checkout_url', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status in ('pending','paid','canceled')"),
    sa.CheckConstraint('amount_cents > 0'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'request_key'),
    sa.UniqueConstraint('provider', 'provider_reference')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_table('platform_admins',
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('platform_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialist_claims',
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status in ('pending','approved','rejected')"),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('subscriptions',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','canceled')"),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id')
    )
    op.create_table('invitations',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'created_by'], ['users.business_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invitations_business_id'), 'invitations', ['business_id'], unique=False)
    op.create_table('join_requests',
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=160), server_default=sa.text("''"), nullable=False),
    sa.Column('engagement', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status in ('pending','approved','rejected')"),
    sa.ForeignKeyConstraint(['business_id', 'invitation_id'], ['invitations.business_id', 'invitations.id'], ),
    sa.ForeignKeyConstraint(['business_id', 'reviewed_by'], ['users.business_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_business_id'), 'join_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_join_requests_identity_id'), 'join_requests', ['identity_id'], unique=False)
    op.create_index('uq_open_join_identity', 'join_requests', ['identity_id'], unique=True, postgresql_where=sa.text("status in ('pending','approved')"))
    op.add_column('businesses', sa.Column('responsible_name', sa.String(length=160), server_default=sa.text("''"), nullable=False))
    op.add_column('businesses', sa.Column('contact', sa.String(length=160), server_default=sa.text("''"), nullable=False))
    op.add_column('businesses', sa.Column('legacy_access', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.alter_column('businesses', 'legacy_access', server_default=sa.false())
    op.add_column('businesses', sa.Column('access_blocked', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('businesses', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('identities', sa.Column('specialist_conflict', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.create_check_constraint('ck_trial_period','businesses',"(trial_started_at IS NULL AND trial_ends_at IS NULL) OR (trial_started_at IS NOT NULL AND trial_ends_at IS NOT NULL AND trial_ends_at > trial_started_at)")
    op.execute("""UPDATE identities SET specialist_conflict=true WHERE id IN
        (SELECT identity_id FROM users GROUP BY identity_id
         HAVING count(DISTINCT business_id)>1 AND bool_or(role='profissional'))""")
    op.execute("""INSERT INTO specialist_claims(identity_id,business_id,status)
        SELECT u.identity_id,u.business_id,'approved' FROM users u JOIN identities i ON i.id=u.identity_id
        WHERE u.role='profissional' AND NOT i.specialist_conflict""")
    op.execute("""CREATE FUNCTION enforce_specialist_company() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='UPDATE' AND NEW.identity_id=OLD.identity_id AND NEW.business_id=OLD.business_id AND NEW.role=OLD.role THEN RETURN NEW; END IF;
      PERFORM id FROM identities WHERE id=NEW.identity_id FOR UPDATE;
      IF EXISTS(SELECT 1 FROM identities WHERE id=NEW.identity_id AND specialist_conflict) THEN
        RAISE EXCEPTION 'Existing specialist links require explicit review' USING ERRCODE='23505';
      END IF;
      IF EXISTS(SELECT 1 FROM users WHERE identity_id=NEW.identity_id AND id<>NEW.id AND business_id<>NEW.business_id
          AND (NEW.role='profissional' OR role='profissional'))
         OR EXISTS(SELECT 1 FROM specialist_claims WHERE identity_id=NEW.identity_id AND business_id<>NEW.business_id AND status<>'rejected') THEN
        RAISE EXCEPTION 'Specialist may only belong to one business' USING ERRCODE='23505';
      END IF;
      RETURN NEW;
    END $$""")
    op.execute("CREATE TRIGGER trg_specialist_company BEFORE INSERT OR UPDATE ON users FOR EACH ROW EXECUTE FUNCTION enforce_specialist_company()")
    # ### end Alembic commands ###

def downgrade():
    # Deliberately fail rather than discard new commercial history on rollback.
    connection=op.get_bind()
    if connection.scalar(sa.text('SELECT count(*) FROM businesses WHERE trial_started_at IS NOT NULL OR access_blocked')):
        raise RuntimeError('Commercial data exists: trial/access history requires a verified backup or forward migration.')
    for table in ('invoices','payment_events','join_requests','invitations','platform_admins','platform_audit','subscriptions'):
        if connection.scalar(sa.text(f'SELECT count(*) FROM {table}')):
            raise RuntimeError('Commercial data exists: restore a verified backup or migrate forward; downgrade would lose history.')
    op.execute('DROP TRIGGER trg_specialist_company ON users')
    op.execute('DROP FUNCTION enforce_specialist_company()')
    op.drop_constraint('ck_trial_period','businesses',type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'specialist_conflict')
    op.drop_column('businesses', 'trial_ends_at')
    op.drop_column('businesses', 'trial_started_at')
    op.drop_column('businesses', 'access_blocked')
    op.drop_column('businesses', 'legacy_access')
    op.drop_column('businesses', 'contact')
    op.drop_column('businesses', 'responsible_name')
    op.drop_index('uq_open_join_identity', table_name='join_requests', postgresql_where=sa.text("status in ('pending','approved')"))
    op.drop_index(op.f('ix_join_requests_identity_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_business_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_invitations_business_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('payment_events')
    op.drop_table('subscriptions')
    op.drop_table('specialist_claims')
    op.drop_table('platform_audit')
    op.drop_table('platform_admins')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
